name: timerapp
description: "모딧 - 생산성 향상을 위한 스마트 타이머 앱"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  device_info_plus: ^11.4.0
  workmanager: ^0.6.0
  url_launcher: ^6.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/timer_app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#F9F7F4"
  adaptive_icon_foreground: "assets/icon/timer_app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
  fonts:
    - family: IM_Hyemin
      fonts:
        - asset: assets/IM_Hyemin-Regular.otf